title: RelaxedMason – Data Analyst Portfolio
description: BAFTA Scripted Comedy Awards Visualization
theme: minima

# tell Jekyll your project slug so "/assets/..." works
baseurl: "/bafta-scripted-comedy-portfolio"

