# _config.yml
title: "Mason Colborn"
theme: minima
url: "https://masoncolborn.com"
baseurl: ""   

defaults:
  - scope:
      path: ""
    values:
      extra_head: "{% include custom-head.html %}"









