title: "Mason Colborn"
theme: minima
url: "https://masoncolborn.com"
baseurl: ""

defaults:
  - scope:
      path: ""            # all files
    values:
      extra_head: "<link rel='stylesheet' href='{{ '/assets/css/custom.css' | relative_url }}' />"


