# _config.yml
title: Mason Colborn – Data Analyst Portfolio
description: "BAFTA Scripted Comedy Awards: Winners & Nominees (2016–2025)"
theme: minima

url: "https://masoncolborn.com"
baseurl: ""

# automatically apply `layout: home` to everything in the repo root
defaults:
  - scope:
      path: ""
    values:
      layout: home
      extra_head: "<link rel='stylesheet' href='/assets/css/custom.css' />"

