title: "Mason Colborn – Data Analyst Portfolio"
description: "SQL • Python • APIs • Dashboarding"
theme: minima

url: "https://masoncolborn.com"
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      extra_head: "<link rel='stylesheet' href='/assets/css/custom.css' />"

