name: Python Sanity
on:
  workflow_dispatch:
jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install -r bafta-scripted-comedy-portfolio/requirements.txt
      - name: Verify imports
        run: python -c "import pandas, requests; print('Imports OK')"
