name: Update Cal Raleigh HR Data

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run fetch script
        run: python scripts/get_raleigh_hr.py
      - name: Show generated files
        run: ls -la assets/data || true
      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(data): update Cal Raleigh HRs [auto]'
          file_pattern: "assets/data/raleigh_hr.json assets/data/raleigh_hr.csv"

